/*
 * Copyright (c) 2024, Alibaba Group;
 * Licensed under the Apache License, Version 2.0 (the "License");
 *
 * ---
 * DECOUPLED REPLAY: Independent NS3 replay binary entry point.
 *
 * This binary replays flow files generated by SimAI coupled simulation.
 * It links ONLY against ns3 libraries -- ZERO astra-sim symbols.
 *
 * Build verification: nm scratch_decoupled_replay_main | grep -i simai
 * Must return EMPTY.
 *
 * CLI arguments:
 *   -f, --flow-file      Path to flow file (required)
 *   -t, --topo-dir       Topology directory (e.g., Spectrum-X_128g_...)
 *   -c, --config         SimAI.conf path (default: topo-dir/SimAI.conf)
 *   -o, --fct-output     FCT output file (default: fct.txt)
 *   -s, --stop-time      Simulator stop time in seconds (default: 2000000000)
 *   --verify-dag         Run DAG cycle detection before simulation
 *   --dump-layer-stats   Output per-layer timing statistics JSON
 */

#include "common_types.h"
#include "flow_reader.h"
#include "topology_reader.h"
#include "flow_sender.h"
#include "fct_writer.h"
#include "dep_scheduler.h"

#include <cstring>
#include <iostream>
#include <csignal>

// Global scheduler pointer for signal handler / early exit reporting
static DepScheduler* g_scheduler = nullptr;

// Signal handler for graceful shutdown (reports partial stats)
static void signal_handler(int sig) {
    std::cerr << "\n[DecoupledReplay] Caught signal " << sig
              << ", shutting down..." << std::endl;
    if (g_scheduler) {
        g_scheduler->VerifyCompletion();
        g_scheduler->DumpBucketStats();
    }
    exit(1);
}

int main(int argc, char *argv[]) {
    // Register signal handlers for graceful shutdown
    std::signal(SIGINT, signal_handler);
    std::signal(SIGTERM, signal_handler);

    // Default paths
    std::string topo_dir = "";
    std::string config_path = "";
    std::string flow_file_path = "";
    double sim_stop_time = 2000000000.0;  // effectively no limit
    bool dump_layer_stats = false;
    bool verify_dag = false;

    // Parse CLI arguments
    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];
        if ((arg == "-t" || arg == "--topo-dir") && i + 1 < argc) {
            topo_dir = argv[++i];
        } else if ((arg == "-c" || arg == "--config") && i + 1 < argc) {
            config_path = argv[++i];
        } else if ((arg == "-f" || arg == "--flow-file") && i + 1 < argc) {
            flow_file_path = argv[++i];
        } else if ((arg == "-o" || arg == "--fct-output") && i + 1 < argc) {
            fct_output_file = argv[++i];
        } else if ((arg == "-s" || arg == "--stop-time") && i + 1 < argc) {
            sim_stop_time = std::stod(argv[++i]);
        } else if (arg == "--verify-dag") {
            verify_dag = true;
        } else if (arg == "--dump-layer-stats") {
            dump_layer_stats = true;
        } else if (arg == "-h" || arg == "--help") {
            std::cout << "Usage: " << argv[0] << " [OPTIONS]\n"
                      << "  -f, --flow-file PATH    Flow file to replay (required)\n"
                      << "  -t, --topo-dir DIR      Topology directory\n"
                      << "  -c, --config PATH       Config file (default: topo-dir/SimAI.conf)\n"
                      << "  -o, --fct-output PATH   FCT output file (default: fct.txt)\n"
                      << "  -s, --stop-time SEC     Simulator stop time (default: 2000000000)\n"
                      << "  --verify-dag            Run DAG cycle detection before simulation\n"
                      << "  --dump-layer-stats      Output per-layer timing statistics\n"
                      << "  -h, --help              Show this help\n";
            return 0;
        }
    }

    if (flow_file_path.empty()) {
        std::cerr << "ERROR: --flow-file is required. Use -h for help." << std::endl;
        return 1;
    }

    // Resolve config and topology paths
    if (config_path.empty()) {
        config_path = topo_dir + "/SimAI.conf";
    }
    std::string topo_xml = topo_dir + "/POD#1.xml";

    // =====================================================================
    // Step 1: Read configuration + apply NS3 defaults
    // =====================================================================
    std::cout << "[DecoupledReplay] Reading configuration..." << std::endl;
    if (!ReadConf(topo_xml, config_path)) {
        std::cerr << "ERROR: ReadConf failed" << std::endl;
        return 1;
    }
    SetConfig();

    // =====================================================================
    // Step 2: Setup NS3 network
    // =====================================================================
    std::cout << "[DecoupledReplay] Setting up network..." << std::endl;
    SetupNetwork(qp_finish, send_finish);

    // =====================================================================
    // Step 3: Load flows from file
    // =====================================================================
    std::cout << "[DecoupledReplay] Loading flows from " << flow_file_path << "..." << std::endl;
    BucketMetaMap bucket_meta;
    int file_send_lat = -1;
    std::vector<FlowFileRecord> flows = LoadFlows(flow_file_path, bucket_meta, &file_send_lat);
    if (flows.empty()) {
        std::cerr << "ERROR: No flows loaded from " << flow_file_path << std::endl;
        return 1;
    }
    std::cout << "[DecoupledReplay] Loaded " << flows.size() << " flows, "
              << bucket_meta.size() << " buckets with metadata." << std::endl;

    // Resolve send_lat: the flow file records the value the coupled export used;
    // AS_SEND_LAT overrides it. Warn loudly on an override mismatch so the
    // export/replay send-latency divergence (which compounds over every ring step)
    // can never happen silently.
    const char* send_lat_source = "default; flow file did not record it";
    if (file_send_lat > 0) { g_replay_send_lat_us = file_send_lat; send_lat_source = "from flow file"; }
    {
        const char* env = std::getenv("AS_SEND_LAT");
        if (env && env[0]) {
            int env_lat = std::atoi(env);
            if (env_lat > 0) {
                if (file_send_lat > 0 && env_lat != file_send_lat) {
                    std::cerr << "[DecoupledReplay] WARNING: AS_SEND_LAT=" << env_lat
                              << "us overrides flow-file send_lat=" << file_send_lat
                              << "us — replay timing will differ from the export run."
                              << std::endl;
                }
                g_replay_send_lat_us = env_lat;
                send_lat_source = "AS_SEND_LAT override";
            }
        }
    }
    std::cout << "[DecoupledReplay] send_lat = " << g_replay_send_lat_us << " us ("
              << send_lat_source << ")" << std::endl;

    // Log bucket metadata
    for (const auto& kv : bucket_meta) {
        std::cout << "[DecoupledReplay]   Job " << kv.second.job_id
                  << " bucket " << kv.second.bucket_id
                  << " (layer=" << kv.second.layer_num
                  << ", loopstate=" << kv.second.loopstate << ")"
                  << ": " << kv.second.total_flows << " flows"
                  << ", compute_before=" << kv.second.compute_before_ns << " ns";
        if (kv.second.compute_before_ns > 0) {
            std::cout << " (" << (kv.second.compute_before_ns / 1000000.0) << " ms)";
        }
        std::cout << std::endl;
    }

    // =====================================================================
    // Step 4: Init DepScheduler
    // =====================================================================
    DepScheduler scheduler;
    g_scheduler = &scheduler;

    if (!scheduler.Init(flows, bucket_meta)) {
        std::cerr << "ERROR: DepScheduler::Init failed" << std::endl;
        return 1;
    }

    // DAG cycle detection — always run. A cyclic parent_flow_id graph is always
    // upstream corruption; without this the cycle's flows keep pending_deps>0
    // forever and the replay silently stalls until the wall-clock stop, reporting
    // incomplete flows instead of failing loud. (--verify-dag is kept as a no-op
    // for back-compat.)
    (void)verify_dag;
    if (!scheduler.VerifyDAG()) {
        std::cerr << "ERROR: DAG verification failed (cycles detected)" << std::endl;
        return 1;
    }

    // Register the flow-completion callback (links qp_finish → DepScheduler)
    g_on_flow_completed = [](uint32_t flow_id) {
        if (g_scheduler) {
            g_scheduler->OnFlowCompleted(flow_id);
        }
    };

    // =====================================================================
    // Step 5: Start the scheduler (unlocks bucket 0, respects its compute gap)
    // =====================================================================
    std::cout << "[DecoupledReplay] Starting scheduler..." << std::endl;
    scheduler.Start();

    // =====================================================================
    // Step 6: Run simulation
    // =====================================================================
    std::cout << "[DecoupledReplay] Running simulation (stop_time="
              << sim_stop_time << "s)..." << std::endl;
    fflush(stdout);
    NS_LOG_INFO("Run Simulation.");

    Simulator::Stop(Seconds(sim_stop_time));
    Simulator::Run();

    // =====================================================================
    // Step 7: Verify completion and output stats
    // =====================================================================
    bool all_completed = scheduler.VerifyCompletion();

    if (dump_layer_stats) {
        scheduler.DumpBucketStats();
    }

    if (!all_completed) {
        std::cerr << "[DecoupledReplay] WARNING: Not all flows completed. "
                  << "Increase --stop-time if flows were still in-flight." << std::endl;
    }

    // =====================================================================
    // Step 8: Cleanup
    // =====================================================================
    g_on_flow_completed = nullptr;
    g_scheduler = nullptr;

    Simulator::Destroy();

    std::cout << "[DecoupledReplay] Done. FCT output: " << fct_output_file << std::endl;
    return all_completed ? 0 : 1;
}
